#!/usr/bin/env bash
# runs nginx as nginx
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx -- service nginx restart
